name: "Pull Request Docs Check"
on: 
  push:
    branches: ['main']

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: latest
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "make html"
        pre-build-command: "pip install -r docs/requirements.txt"
