name: Deploy documents

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'
      - name: Install Python dependency
        working-directory: docs
        run: pip install -r requirements.txt
      - name: Build HTML
        working-directory: docs
        run: |
          make clean
          make html
      - name: List result
        run: ls docs/build/html
