name: "Pull Request Docs Check"
on: 
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11

    - name: Install dependencies
      working-directory: ./docs
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build pages
      working-directory: ./docs
      run: make html

    - name: Make artifact
      working-directory: ./docs
      run: tar -cf "$RUNNER_TEMP/artifact.tar" ./build/html

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        path: ./docs/build/html

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write
    
    runs-on: ubuntu-latest
    steps:

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.5
